apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1 # Number of desired replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # You can specify a different version if needed
        ports:
        - containerPort: 80  # Port on which Nginx will listen

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Use an internal load balancer
spec:
  selector:
    app: nginx  # Label selector to match the Nginx deployment
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port to forward traffic to in the pods
  type: LoadBalancer

